### ISSUE TITLE
Change name to imply new ownership, differentiate

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/import-export-tools#2]
It has been raised that we should adjust the name to imply the development of the add-on being taken over by someone else, and differentiate between Paolo's.

Ideas? Suggestions?

**Comment by cleidigh** [comment]
The list discussions seem to indicate that legally we do not have to change the name.
It may be advantageous to do so anyway, especially since this is not a functional problem like the ID.
Off the top of my head:
- Import/Export Utilities (or Utils)
- Import/Export Data tools, utilities...
- Thunderbird Import/Export

I also think that the icon should change.  I can look for one I like doing that stuff.

Some of the ideas thrown out concerning abandoned extensions are definitely good.  I think that process is at the top of the priority list to make this transition smoothly.  I hope we can have that in place for 68.

**Comment by Sancus** [comment]
We can (maybe) do a server side hack that auto-updates Import Export Tools for 68, but any kind of actual general process for pointing users of abandoned add-ons to alternatives is definitely not possible for 68. 68 release is in a month, and we should be pretty much feature locked at this point, although I don't know the exact status.

A generalized process will almost certainly require client side changes, and will definitely require significant testing and probably before any of that, discussion on how exactly it should work and how much manual user intervention it should take.

**Comment by cleidigh** [comment]
@Sancus 
Yeah, I should not have indicated adding something to 68.  I think I was more concerned about just having something to get people to the right place IF we have to change the ID.  I am back-and-forth in my head about "taking" a developers extension.  If I put on my Machiavellian hat and recognize that several of us have been trying to communicate with the author without success, I could arrive at the conclusion that the greater good of the user base supports us to take it over knowing what happens if we don't.

Certainly from everybody's perspective except the original developer, we should take over the ID and support the users.  I have no problem understanding developers who cannot continue with their work.  Ignoring the issue and not responding as unacceptable and frankly makes me more inclined to just "do it" FWIW

**Comment by cleidigh** [comment]
Changed:
ImportExportTools NG

Also created new icon
